---
#- template: src=iptables.conf.j2 dest=/etc/sysconfig/iptables
#  check_mode: no
#
#- shell: iptables-restore < /etc/sysconfig/iptables
#  check_mode: no

- name: Check iptables version
  test_rpm: "name={{ test_iptables_version }} state=present"
  notify: show_test_failed_message

- name: Check iptables service state and enabled
  test_service: name=iptables defined=True state=started enabled=True
  notify: show_test_failed_message

- test_iptables: src=iptables.conf.j2
  notify: show_test_failed_message

#- name: Create a temporary filename for iptables-save result
#  shell: echo -n /tmp/iptables-config.pid$$-`date +%Y-%m-%dT%H:%M:%S`
#  register: test_iptables_config_save_result_filename
#  changed_when: False
#  check_mode: no
#  args:
#    warn: no
#
#- name: Save iptables-save result to the temporary file
#  shell: /usr/sbin/iptables-save | sed -e '/^#/d;/^:/s/\[[0-9][0-9]*:[0-9][0-9]*\]$/[0:0]/g' > {{ test_iptables_config_save_result_filename.stdout }}
#  changed_when: False
#  check_mode: no
#  args:
#    warn: no
#
#- name: Compare iptables template to iptables-save result
#  template: src=iptables.conf.j2 dest={{ test_iptables_config_save_result_filename.stdout }}
#
#- name: Remove iptables-save result temporary file
#  file: path={{ test_iptables_config_save_result_filename.stdout }} state=absent
#  changed_when: False
#  check_mode: no
#
