---
test_nginx_version_list:
  centos6: nginx-1.11.9-7.el6.ngx.x86_64
  centos7: nginx-1.11.9-7.el7.centos.ngx.x86_64
test_nginx_version: "{{ test_nginx_version_list[inventory_hostname] }}"

test_nginx_service_started_list:
  centos7: False
test_nginx_service_state: "{% if test_nginx_service_started_list[inventory_hostname] %}active{% else %}unknown{% endif %}"

test_nginx_service_enabled_list:
  centos7: False
test_nginx_service_enabled: "{% if test_nginx_service_enabled_list[inventory_hostname] %}enabled{% else %}disabled{% endif %}"

worldwide_allowed_ports:
  - 80
  - 443

allowed_ports_for_specific_addresses:
  - { address: 192.168.1.0/24, port: 22 }
