---
test_nginx_version_list:
  centos7: nginx-1.11.10-1.el7.ngx.x86_64
test_nginx_version: "{{ test_nginx_version_list[ansible_hostname] }}"

test_nginx_service_started_list:
  centos7: False
test_nginx_service_state: "{% if test_nginx_service_started_list[ansible_hostname] %}active{% else %}unknown{% endif %}"

test_nginx_service_enabled_list:
  centos7: False
test_nginx_service_enabled: "{% if test_nginx_service_enabled_list[ansible_hostname] %}enabled{% else %}disabled{% endif %}"

worldwide_allowed_ports:
  - 80
  - 443

allowed_ports_for_specific_addresses:
  - { address: 192.168.0.0/24, port: 22 }
