---
- name: Check nginx version
  test_rpm: "name={{ test_nginx_version }} state=present"
  notify: show_test_failed_message

- name: Check nginx pidfile
  test_pidfile: name=/var/run/nginx.pid pattern=nginx state=present match_full=True
  notify: show_test_failed_message

- name: Check nginx process
  test_ps: name=nginx state=present
  args:
    match_full: True
  notify: show_test_failed_message

- name: Check lsyncd process does not exist
  test_ps: name=lsyncd state=absent
  notify: show_test_failed_message

- name: Check nginx service state and enabled
  test_service: name=nginx defined=True state=started enabled=True
  notify: show_test_failed_message

